# Generated by Django 4.2.23 on 2025-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(help_text='Amount in the smallest currency unit (e.g., cents)')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(default='created', max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
