# Generated by Django 4.2.23 on 2025-08-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0002_remove_payment_amount_remove_payment_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compliance_status', models.BooleanField(default=False)),
                ('sent_via', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order')),
            ],
            options={
                'db_table': 'invoices',
                'indexes': [models.Index(fields=['order', '-created_at'], name='invoices_order_i_d68953_idx')],
            },
        ),
    ]
