# Generated by Django 4.2.23 on 2025-09-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0004_invoice_customer_name_invoice_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('credit', 'credit'), ('refund', 'refund')], max_length=10)),
                ('amount_halalah', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'wallet_transactions',
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='wallet_tran_restaur_5656d8_idx'), models.Index(fields=['order'], name='wallet_tran_order_i_f9d811_idx')],
            },
        ),
    ]
