# Generated by Django 4.2.23 on 2025-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo'),
        ),
    ]
