# Generated by Django 4.2.23 on 2025-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_website_domain_website_slug_website_subdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
