# Generated by Django 4.2.23 on 2025-08-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_website_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, default='site-temp', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
