# Generated by Django 4.2.23 on 2025-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_alter_website_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
