# Generated by Django 4.2.23 on 2025-08-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_alter_website_slug'),
    ]

    operations = [
    ]
