# Generated by Django 4.2.23 on 2025-08-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_rename_logo_to_logo_text'),
    ]

    operations = [
    ]
