# Generated by Django 4.2.23 on 2025-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_populate_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
