# Generated by Django 4.2.23 on 2025-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_website_logo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='logo_file',
        ),
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
