# Generated by Django 4.2.23 on 2025-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_remove_website_logo_file_alter_website_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140, unique=True),
        ),
    ]
