# Generated by Django 4.2.23 on 2025-08-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('RestaurantOwner', 'Restaurant Owner'), ('Staff', 'Staff'), ('Customer', 'Customer'), ('Cashier', 'Cashier')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
