# Generated by Django 4.2.23 on 2025-08-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0002_profile_restaurant_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.branch'),
        ),
    ]
