# Generated by Django 4.2.23 on 2025-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('RestaurantOwner', 'Restaurant Owner'), ('BranchManager', 'Branch Manager'), ('Customer', 'Customer'), ('Cashier', 'Cashier')], max_length=20),
        ),
    ]
