# Generated by Django 4.2.23 on 2025-08-29 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('menu', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Size, Add-ons, Spice Level', max_length=100)),
                ('selection_type', models.CharField(choices=[('SINGLE', 'Single Choice'), ('MULTIPLE', 'Multiple Choices')], default='SINGLE', max_length=10)),
                ('is_required', models.BooleanField(default=False, help_text='Customer must make a selection from this group.')),
                ('min_selection', models.PositiveIntegerField(default=0, help_text='Minimum number of options customer must select (for multiple choice).', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_selection', models.PositiveIntegerField(default=1, help_text='Maximum number of options customer can select (for multiple choice).', validators=[django.core.validators.MinValueValidator(1)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Positive value to add to price, negative to subtract.', max_digits=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.optiongroup')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='option_groups',
            field=models.ManyToManyField(blank=True, related_name='products', to='menu.optiongroup'),
        ),
    ]
