# Generated by Django 4.2.23 on 2025-08-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_optiongroup_option_product_option_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='selection_type',
            field=models.CharField(choices=[('SINGLE', 'خيار واحد'), ('MULTIPLE', 'خيارات متعددة')], default='SINGLE', max_length=10),
        ),
    ]
