# Generated by Django 4.2.23 on 2025-09-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0002_order_guest_name_order_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineindetails',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.branch'),
        ),
        migrations.AlterField(
            model_name='pickupdetails',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.branch'),
        ),
    ]
