# Generated by Django 4.2.23 on 2025-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dineindetails_branch_alter_pickupdetails_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dineindetails',
            name='reservation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickupdetails',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
